### ISSUE TITLE
Variable Assignment Error

### ISSUE THREAD

**Issue by sawyerru** [hdevalence/ed25519consensus#13]
Hello, 

This package is a lower dependency in my project and on runtime, this error is occuring:

`# github.com/hdevalence/ed25519consensus
..\..\..\..\..\go\pkg\mod\github.com\hdevalence\ed25519consensus@v0.0.0-20210204194344-59a8610d2b87\batch.go:54:4: assignment mismatch: 1 variable but new(edwards25519.Scalar).SetUniformBytes returns 2 values
..\..\..\..\..\go\pkg\mod\github.com\hdevalence\ed25519consensus@v0.0.0-20210204194344-59a8610d2b87\ed25519.go:42:11: assignment mismatch: 
1 variable but new(edwards25519.Scalar).SetUniformBytes returns 2 values`

Was this issue fixed in a separate commit? it looks like my dependency is locked onto a particular commit hash.

Thanks for any info.

**Comment by sawyerru** [comment]
This issue would will be resolved once PR is merged

**Comment by yifanes** [comment]
@sawyerru Have you solved this problem? I also encountered this problem

**Comment by FiloSottile** [comment]
This was fixed by #12, make sure you're using version v0.0.0-20220222234857-c00d1f31bab3 or later.
