### ISSUE TITLE
Implement batch verification

### ISSUE THREAD

**Issue by hdevalence** [hdevalence/ed25519consensus#5]
The library should have a batch verification API, similar to the one in `ed25519-zebra`: https://docs.rs/ed25519-zebra/2.2.0/ed25519_zebra/batch/index.html

Batch verification should be done in init-update-finalize (IUF) style, as in that crate, allowing users to:

1. Create a batch verification context;
2. Add items to the batch;
3. Compute the batch verification result.

The Rust API linked above does this, with an additional detail that it uses an `Item` type in step (2) rather than passing the signature/verificationkey/message triple directly.  In Rust, this allows the challenge scalar to be computed upfront, so that the lifetime of the batch verification context is not linked to the lifetime of the message (which is probably borrowed data).  Because Go is garbage-collected, this is unnecessary, so step (2) can just take the signature/verificationkey/message triple.

To implement batch verification, the `ed25519-zebra` code is a good example, because it includes an extra optimization that is even more efficient for the case where multiple signatures come from the same public keys: https://docs.rs/ed25519-zebra/2.2.0/src/ed25519_zebra/batch.rs.html#149-217

**Comment by hdevalence** [comment]
I'd be happy to mentor anyone who's interested in working on this, just let me know.

**Comment by tac0turtle** [comment]
@FiloSottile I couldn't find `MulByCoFactor` in your lib, any chance you could implement it?

**Comment by FiloSottile** [comment]
Hmm, not sure if we should make a method for it, I tried to avoid getting into cofactor discussions in the API, but in the meantime you can just double three times: https://github.com/hdevalence/ed25519consensus/blob/7fde80a9d5ff543c8e2d304c4b5d7312459922fe/ed25519.go#L62-L64

**Comment by tac0turtle** [comment]
Went with this approach for now. It would be a nice to have since its possible other ways. A second nice to have would be a `IsIdentity` method instead of `NewIdentityPoint` then `Point.Equal`.

**Comment by FiloSottile** [comment]
Spent some time thinking about it, and I'll add a method for cofactor multiplication, but not for the identity check, at least for now. The triple `Add` chain is flow breaking and obscures meaning, while the `Equal` check might be a bit ugly but is clear what it's doing, and having a method only to check this one value feels unbalanced (like, why not `Scalar.IsZero` and `IsGenerator` too, and why would this return `bool` while `Equal` returns `int` to make constant time code possible).

**Comment by tac0turtle** [comment]
🙏 thanks, that would be awesome. Understandable on the `IsIdentity`.

**Comment by FiloSottile** [comment]
There is now `MultByCofactor` in v1.0.0-beta.2!

**Comment by lukechampine** [comment]
@marbar3778 are you still working on this? I have [an implementation](https://github.com/lukechampine/us/blob/master/ed25519hash/batch.go) that's passing tests, but the API is a bit different, so feel free to copy+adjust as needed.
